version: '3'

services:
  front:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    volumes:
      - .:/home/docker:ro
      - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
      - phpmyadmin:/var/www
    depends_on:
      - engine
    
  engine:
    build: ./docker/engine/
    ports:
      - 9000:9000
    volumes:
      - .:/home/docker:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    depends_on:
      - database
  
  database:
    build: ./docker/database/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=toto
      - MYSQL_USER=toto
      - MYSQL_PASSWORD=pwd
      # Allow empty password for the root user
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker/database/db:/var/lib/mysql

  phpmyadmin:
    # image: phpmyadmin/phpmyadmin
    build: ./docker/phpMyAdmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=database
      - PMA_PORT=3307
    volumes:
      - phpmyadmin:/var/www   
    depends_on:
      - database
    # restart: always
    # ports:
    #  - 8080:80
    # volumes:
    #  - /sessions

volumes:
  phpmyadmin: